### ISSUE TITLE
Windows Compability

### ISSUE THREAD

**Issue by barbar10** [Cruze03/FakeRanks-RevealAll#1]
There is any chance for update for windows OS ?

Your plugin cause my server to crash since it doesn't coordinated for windows and only for linux

i checked twice and tried to delete the plugin and it definitly was the cause , anyways i would like to get a version for Windows OS of this plugin

**Comment by barbar10** [comment]
> Hey! Thanks for reporting. I will look into it and test with windows

any updates mate ?

**Comment by Cruze03** [comment]
Hey! @barbar10 It was K4-System-MMRanks which was crashing the windows server. Try this:
[K4-System-MMRanks.zip](https://github.com/Cruze03/FakeRanks-RevealAll/files/15033277/K4-System-MMRanks.zip)

You can build yourself from here: https://github.com/K4ryuu/K4-System-MMRanks/pull/4

**Comment by barbar10** [comment]
This is working fine ! Thank you so much you are amazing !!!
