### ISSUE TITLE
Latest cs2update 24/05/2024

### ISSUE THREAD

**Issue by chycken** [Cruze03/FakeRanks-RevealAll#3]
Hi, can you update the plugin please? Plugin is broken bc of the latest cs2update

**Comment by mihaigsm2003** [comment]
> Will look into it tomorrow!

waiting for update, thx!

**Comment by Cruze03** [comment]
@chycken @mihaigsm2003 
Here you go. Let me know how it goes. Also would be nice if you mention which platform you tested on.
https://github.com/Cruze03/FakeRanks-RevealAll/releases/latest

**Comment by msk-01** [comment]
Hello, this still doesn't show premier points of other players for me (I can see only mine).

I'm on Linux, metamod 1290, using latest CSS/K4-System

I can try to provide more info / debug if needed. Thanks a lot

**Comment by Cruze03** [comment]
Hey @msk-01 Missed calling a function. Can you try again with the latest version. If still not working, post a screenshot of meta list here.

**Comment by chycken** [comment]
> Hey @msk-01 Missed calling a function. Can you try again with the latest version. If still not working, post a screenshot of meta list here.

its working well now, thanks

**Comment by Cruze03** [comment]
Great. Closing this issue now.
