### ISSUE TITLE
Latest cs2 update

### ISSUE THREAD

**Issue by chycken** [Cruze03/FakeRanks-RevealAll#4]
Hi, latest cs2 update broke this plugin too. Could u fix it please?

**Comment by Cruze03** [comment]
Yes, waiting for update from hl2sdk-cs2

**Comment by Truyn** [comment]
:(

**Comment by mayersgamer** [comment]
:(

**Comment by Cruze03** [comment]
https://github.com/Cruze03/FakeRanks-RevealAll/releases/latest

**Comment by mayersgamer** [comment]
hey guys is it working for you latest version ?

**Comment by mayersgamer** [comment]
> Can you be more specific? Is the plugin crashing the server? What is happening exactly?

Listing 3 plugins:
  [01] ServerListPlayersFix (1.0.1) by Poggu
  [02] <ERROR>
  [03] CounterStrikeSharp (v239 @ a695eec) by Roflmuffin

**Comment by mayersgamer** [comment]
its working
