### ISSUE TITLE
Update cs2, crash plugin

### ISSUE THREAD

**Issue by Truyn** [Cruze03/FakeRanks-RevealAll#5]
Need update!

**Comment by 1370533448** [comment]
Yes, the recent update caused the plugin to crash

**Comment by Cruze03** [comment]
https://github.com/Cruze03/FakeRanks-RevealAll/releases/tag/v1.0.6

**Comment by 1370533448** [comment]
> https://github.com/Cruze03/FakeRanks-RevealAll/releases/tag/v1.0.6

Hello, is the plugin available after the update? It doesn't crash now, but I still can't see the scores of other players

**Comment by 1370533448** [comment]
After my testing, during the warm-up before the game starts or at the end of the game, the scores of all players will be displayed, and at one point, the score of a player from the opposing team appeared

**Comment by Cruze03** [comment]
Will notify when I find a fix

**Comment by Cruze03** [comment]
Tested out latest version. Works fine. Try again
