### ISSUE TITLE
is okey its not showing in meta list windows version 

### ISSUE THREAD

**Issue by mayersgamer** [Cruze03/FakeRanks-RevealAll#6]
linux is showing up but windows doesnt show in the list 

> meta list
[Client]   [01] CounterStrikeSharp (v0 @ ce3ff44) by Roflmuffin
[Client]   [02] ServerListPlayersFix (1.0.1) by Poggu

**Comment by Cruze03** [comment]
I have tested plugin in both platforms. Works well for me. I would need more details

**Comment by mayersgamer** [comment]
its working thank you i was uploading the windows version to my linux server ......
